apiVersion: v1
kind: Service
metadata:
  name: {{ include "helpers.build-name" (merge (dict "name" "mongo") .) }}
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector: {{ include "helpers.static-labels" (merge (dict "name" "mongo") .) | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.build-name" (merge (dict "name" "mongo") .) }}
  labels: {{ include "helpers.labels" (merge (dict "name" "mongo") .) | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "helpers.labels" (merge (dict "name" "mongo") .) | nindent 6 }}
  template:
    metadata:
      labels: {{ include "helpers.labels" (merge (dict "name" "mongo") .) | nindent 8 }}
    spec:
      containers:
      - name: mongo
        image: {{ include "helpers.build-image" (merge (dict "name" "mongo") .) }}
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
      resources: {{ toYaml .Values.resources.redis | nindent 10 }}
{{- with .Values.nodeSelector.redis }}
      nodeSelector: {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity.redis }}
      affinity: {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations.redis }}
      tolerations: {{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: {{ include "helpers.build-name" (merge (dict "name" "mongo-data") .) }}
