apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helpers.build-name" (merge (dict "name" "redis-data") .) }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "{{ .Values.pvcs.redis.storageClassName }}"
