apiVersion: v1
kind: Service
metadata:
  name: {{ include "helpers.build-name" (merge (dict "name" "redis") .) }}
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector: {{ include "helpers.static-labels" (merge (dict "name" "redis") .) | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.build-name" (merge (dict "name" "redis") .) }}
  labels: {{ include "helpers.labels" (merge (dict "name" "redis") .) | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "helpers.static-labels" (merge (dict "name" "redis") .) | nindent 6 }}
  template:
    metadata:
      labels: {{ include "helpers.labels" (merge (dict "name" "redis") .) | nindent 8 }}
    spec:
      containers:
      - name: redis
        image: {{ include "helpers.build-image" (merge (dict "name" "redis") .) }}
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources: {{ toYaml .Values.resources.redis | nindent 10 }}
{{- with .Values.nodeSelector.redis }}
      nodeSelector: {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity.redis }}
      affinity: {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations.redis }}
      tolerations: {{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ include "helpers.build-name" (merge (dict "name" "redis-data") .) }}
