apiVersion: v1
kind: Service
metadata:
  name: {{ include "helpers.build-name" (merge (dict "name" "middleware") .) }}
  labels: {{ include "helpers.static-labels" (merge (dict "name" "middleware") .) | nindent 4 }}
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - targetPort: 3500
    port: {{ .Values.service.port }}
    name: http
  selector: {{ include "helpers.static-labels" (merge (dict "name" "middleware") .) | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.build-name" (merge (dict "name" "config") .) }}
data:
  # override the redis host
  config.json: >
    {{ toJson (merge (dict "db" (dict "mongo" (dict "uri" (printf "mongodb://%s:27017" (include "helpers.build-name" (merge (dict "name" "mongo") .)))) "redis" (dict "host" (include "helpers.build-name" (merge (dict "name" "redis") .))))) .Values.middlewareConfig) }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "helpers.build-name" (merge (dict "name" "middleware") .) }}
  labels: {{ include "helpers.labels" (merge (dict "name" "middleware") .) | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "helpers.static-labels" (merge (dict "name" "middleware") .) | nindent 6 }}
  template:
    metadata:
      labels: {{ include "helpers.labels" (merge (dict "name" "middleware") .) | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: speedrun-browser
        image: {{ include "helpers.build-image" (merge (dict "name" "middleware") .) }}
        imagePullPolicy: Always
        tty: true
        stdin: true
        volumeMounts:
        - name: config
          mountPath: /speedrunbrowser-middleware/config
        - name: secrets
          mountPath: /speedrunbrowser-middleware/secrets
        ports:
        - containerPort: 3500
          name: http
        resources: {{ toYaml .Values.resources.redis | nindent 10 }}
{{- with .Values.nodeSelector.redis }}
      nodeSelector: {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity.redis }}
      affinity: {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations.redis }}
      tolerations: {{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "helpers.build-name" (merge (dict "name" "config") .) }}
      - name: secrets
        secret:
          secretName: {{ .Values.middlewareSecretName }}
